name: Go

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 */1 * *"

env:
  GO111MODULE: on

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build
        run: go build -o main .
      - name: Run
        run: ./main
      - name: Update README and Push
        run: |
          git config user.name zhoukuncheng
          git config user.email zhoukun.dev@gmail.com
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "[gh-action] Update README"
          git push origin master